# Generated by Django 2.2.1 on 2019-05-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190517_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_data',
            new_name='created_data',
        ),
    ]
